import { connectDB } from "./mongodb";
import Car from "../models/Car";
import { fetchMobileCars } from "./mobile";

export const syncCars = async () => {
  await connectDB();
  const ads = await fetchMobileCars();

  const ops = ads.map((ad) => {
    const {
      vin,
      make,
      model,
      modelDescription,
      firstRegistration,
      mileage,
      power,
      cubicCapacity,
      gearbox,
      fuel,
      images = [],
      price = {},
      category,
      climatisation,
      airbag,
      ambientLighting,
      onBoardComputer,
      paddleShifters,
      usb,
      driveType,
      consumptions,
      emissions,
      seats,
      doors,
      emissionClass,
      newHuAu,
      parkingAssistants,
      manufacturerColorName,
      exteriorColor,
      interiorType,
      interiorColor,
      tintedWindows,
      armRest,
      heatedWindshield,
      electricWindows,
      electricTailgate,
      electricExteriorMirrors,
      foldingExteriorMirrors,
      electricAdjustableSeats,
      memorySeats,
      leatherSteeringWheel,
      panoramicGlassRoof,
      sunroof,
      keylessEntry,
      electricHeatedSeats,
      centralLocking,
      headUpDisplay,
      multifunctionalWheel,
      powerAssistedSteering,
      bluetooth,
      cdPlayer,
      handsFreePhoneSystem,
      wirelessCharging,
      navigationSystem,
      voiceControl,
      touchscreen,
      radio,
      alarmSystem,
      abs,
      distanceWarningSystem,
      glareFreeHighBeam,
      immobilizer,
      esp,
      highBeamAssist,
      speedLimiter,
      isofix,
      lightSensor,
      frontFogLights,
      collisionAvoidance,
      emergencyCallSystem,
      automaticRainSensor,
      tirePressureMonitoring,
      laneDepartureWarning,
      startStopSystem,
      tractionControlSystem,
      trafficSignRecognition,
      daytimeRunningLamps,
      headlightType,
      bendingLightsType,
      headlightWasherSystem,
      summerTires,
      alloyWheels,
      sportPackage,
      sportSeats,
    } = ad;

    return {
      updateOne: {
        filter: { vin },
        update: {
          $set: {
            vin,
            make,
            model,
            modelDescription,
            firstRegistration,
            mileage,
            power,
            cubicCapacity,
            gearbox,
            fuel,
            images: images.slice(0, 20).map((img) => ({
              ref: img.ref,
              hash: img.hash || "",
            })),
            price: {
              consumerPriceGross: price.consumerPriceGross || "",
              type: price.type || "",
              currency: price.currency || "",
            },
            category,
            climatisation,
            airbag,
            ambientLighting,
            onBoardComputer,
            paddleShifters,
            usb,
            driveType,
            consumptions,
            emissions,
            seats,
            doors,
            emissionClass,
            newHuAu,
            parkingAssistants,
            manufacturerColorName,
            exteriorColor,
            interiorType,
            interiorColor,
            tintedWindows,
            armRest,
            heatedWindshield,
            electricWindows,
            electricTailgate,
            electricExteriorMirrors,
            foldingExteriorMirrors,
            electricAdjustableSeats,
            memorySeats,
            leatherSteeringWheel,
            panoramicGlassRoof,
            sunroof,
            keylessEntry,
            electricHeatedSeats,
            centralLocking,
            headUpDisplay,
            multifunctionalWheel,
            powerAssistedSteering,
            bluetooth,
            cdPlayer,
            handsFreePhoneSystem,
            wirelessCharging,
            navigationSystem,
            voiceControl,
            touchscreen,
            radio,
            alarmSystem,
            abs,
            distanceWarningSystem,
            glareFreeHighBeam,
            immobilizer,
            esp,
            highBeamAssist,
            speedLimiter,
            isofix,
            lightSensor,
            frontFogLights,
            collisionAvoidance,
            emergencyCallSystem,
            automaticRainSensor,
            tirePressureMonitoring,
            laneDepartureWarning,
            startStopSystem,
            tractionControlSystem,
            trafficSignRecognition,
            daytimeRunningLamps,
            headlightType,
            bendingLightsType,
            headlightWasherSystem,
            summerTires,
            alloyWheels,
            sportPackage,
            sportSeats,
          },
        },
        upsert: true,
      },
    };
  });

  if (ops.length) {
    const result = await Car.bulkWrite(ops);
    console.log(
      `🔄 Synced ${
        result.nUpserted + result.nModified
      } cars to match full schema`
    );
  }
};
